### ISSUE TITLE
Error when try to show the animation

### ISSUE THREAD

**Issue by Arthur151** [PeizhuoLi/neural-blend-shapes#1]
Great work!
When I try to visualize the animation via blender following [this](https://github.com/PeizhuoLi/neural-blend-shapes#animation), an error occured.

```
Saved: '../demo/images/0000.png'
 Time: 00:00.28 (Saving: 00:00.25)

Traceback (most recent call last):
  File "/home/yusun/Documents/GitHub/neural-blend-shapes/blender_scripts/render_mesh.py", line 96, in <module>
    batch_render(args.obj_path)
  File "/home/yusun/Documents/GitHub/neural-blend-shapes/blender_scripts/render_mesh.py", line 56, in batch_render
    render_obj(os.path.join(dir, file))
  File "/home/yusun/Documents/GitHub/neural-blend-shapes/blender_scripts/render_mesh.py", line 42, in render_obj
    obj.select_set(True)
AttributeError: 'Object' object has no attribute 'select_set'
```

I am using Blender v2.91a. Any suggestion?

**Comment by PeizhuoLi** [comment]
Hi, for the rendering part, could it be the case that the default `blender` command in your environment does not point to the v2.91a version? If it's the case you can try to add it to $PATH or use the full path to your blender executable file. 

Regarding the pose parameters, the answer is yes. The `test_pose` variable [here](https://github.com/PeizhuoLi/neural-blend-shapes/blob/2bd7e193440b9f36361f468c4e51125b9ce6ebbf/demo.py#L120) uses exactly the same pose parameters as in SMPL.

**Comment by CrossLee1** [comment]
when I ran `blender.exe -P vertex_color.py` in Win10 with Blender 2.92.0, it says

`File "D:\SMPL\neural-blend-shapes-main\blender_scripts\vertex_color.py", line 95, in <module>

    bpy.context.space_data.shading.type = 'MATERIAL'

AttributeError: 'NoneType' object has no attribute 'shading' `

How to solve this. Thanks~

**Comment by CrossLee1** [comment]
@PeizhuoLi 
works well now, thanks for your timely reply ~
