### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kaswani29** [PeizhuoLi/neural-blend-shapes#16]
Hi, 

Amazing work. Can you please add license to the repo.

Thanks!!

**Comment by PeizhuoLi** [comment]
Hi, Thanks for your suggestion. Currently part of our code was adapted from the [smpl_pytorch](https://github.com/gulvarol/smplpytorch) project and it is licensed under GPL-v3. This left me no choice to license our project under GPL. But this is not my original plan. I'll re-write those code and put a BSD license soon.

**Comment by PeizhuoLi** [comment]
Now the license has been added so I'm closing the issue.
