### ISSUE TITLE
fbx is fixed on root node?

### ISSUE THREAD

**Issue by foocker** [PeizhuoLi/neural-blend-shapes#19]
how to change the blender script to get the running fbx, not fix one point?

**Comment by PeizhuoLi** [comment]
Hi, there is no need to change the blender script. The global position is recorded in the exported bvh file, which is written by [this](https://github.com/PeizhuoLi/neural-blend-shapes/blob/6d108309bf6892240e5c15b527bc4f5178afed9a/demo.py#L118) call. It is eventually written by [this](https://github.com/PeizhuoLi/neural-blend-shapes/blob/6d108309bf6892240e5c15b527bc4f5178afed9a/dataset/bvh_writer.py#L78) call, with the `pos` variable. I would suggest you to pass the global position to this variable by adding some parameters.

**Comment by foocker** [comment]
> 
soory, not understand..i see pos variable, but, how put it to blender fbx to get the animation in code?
