### ISSUE TITLE
penetration occur when use a fat person

### ISSUE THREAD

**Issue by visonpon** [PeizhuoLi/neural-blend-shapes#20]
Hi @PeizhuoLi, thanks for sharing this wonderful work ,and I have try some obj with different shapes, but encountered penetration problem.
it seems this situation didn't discuss in the paper, can you give some advice? thanks~

**Comment by PeizhuoLi** [comment]
Hi, it is possible that for some extreme cases our method cannot handle them perfectly. Under such circumstances, some manual intervention (e.g., manually creating blend shapes to avoid penetration) might be necessary.
