### ISSUE TITLE
骨骼的坐标系问题

### ISSUE THREAD

**Issue by JunfengLiu1** [PeizhuoLi/neural-blend-shapes#25]
作者您好！当我运行这个命令`python demo.py --animated_bvh=0 --obj_output=0
cd blender_scripts
blender -b -P nbs_fbx_output.py -- --input ../demo --output ../demo/output.fbx`
后，我得到了T-pose的fbx文件。但我把它导入unity时，我发现几乎所有骨骼的坐标系都不与unity重合。而标准的smpl的初始骨骼坐标系应该都与unity坐标系平行。这导致我无法用smpl的姿态参数去驱动使用neural-blend-shapes绑定后的骨骼。请问有什么方法可以在不改变T-pose的姿态下将所有骨骼坐标系都与unity对齐吗？
这是标准的smpl：
![2023-02-04 11-29-37 的屏幕截图](https://user-images.githubusercontent.com/122666174/216745843-bda8f540-c265-4d94-b8e7-f6526f2fb69f.png)
这是用neural-blend-shapes绑定后的：
![2023-02-04 11-35-27 的屏幕截图](https://user-images.githubusercontent.com/122666174/216746018-5a0e1e0b-bf4a-403d-96b6-7ae9a5d52890.png)
这是启动参数：
![2023-02-04 11-32-32 的屏幕截图](https://user-images.githubusercontent.com/122666174/216745926-83a0b935-e6aa-4cae-ba47-0a6694c1dffc.png)

**Comment by Kirstihly** [comment]
My guess is there are some offsets while loading the animation: [loc[..., 1] += 1.1174](https://github.com/PeizhuoLi/neural-blend-shapes/blob/main/dataset/load_test_anim.py#L10)
