### ISSUE TITLE
maya

### ISSUE THREAD

**Issue by yangtao19920109** [PeizhuoLi/neural-blend-shapes#3]
hello,I am a student of USTB,Thanks for excite project,I want to apply your project to maya, but I can't understand rig,I make a FBX file and run this code to get blendshape values,But with the wrong rig,the results is a bit bad, if you have made a fbx file?

**Comment by PeizhuoLi** [comment]
Hi, we haven't tried to integrate everything within an FBX file. Since the neural blend shapes requires evaluating a small MLP network, it's not a straightforward work. PS. You are welcome to discuss with me in Chinese : )

**Comment by yangtao19920109** [comment]
你的工程可以生成一个FBX文件，我这边暂时没有打通怎样把blendshape用代码写进fbx文件。这个代码输入的obj文件，所有的顶点的数值必须归一化到0-1之间吗？

**Comment by yangtao19920109** [comment]
运行代码时，输入的obj文件需要对齐3D模型的空间顶点，这个是怎么做到的？

**Comment by PeizhuoLi** [comment]
你好，目前根据我们的了解暂时无法直接将生成的结果集成到fbx文件中

输入的3D模型可以先尝试通过启用--normalize=1参数进行自动对齐，具体代码见[这里](https://github.com/PeizhuoLi/neural-blend-shapes/blob/41c4473a58330a615e720b15fb56abedbc7fa12a/models/boundingbox.py#L32)。如果效果不佳的话也可以尝试和给出的`eval_constant/meshes/smpl_std.obj`手动对齐，推荐的对齐方式为将手部高度以及手臂长度对齐。

**Comment by yangtao19920109** [comment]
非常感谢
