### ISSUE TITLE
Miko has lifted skeleton

### ISSUE THREAD

**Issue by fire** [PeizhuoLi/neural-blend-shapes#9]
[miko_siggraph_neural_blend_shapes.zip](https://github.com/PeizhuoLi/neural-blend-shapes/files/6677182/miko_siggraph_neural_blend_shapes.zip)

python demo.py --pose_file=./eval_constant/sequences/house-dance.npy --obj_path=./eval_constant/meshes/miko.obj --normalize=1 --obj_output=0 --animated_bvh=1 

![Screenshot from 2021-06-18 06-08-54](https://user-images.githubusercontent.com/32321/122565756-b11ada00-cffb-11eb-9f46-004f14ac4e0b.png)

**Comment by fire** [comment]
Seems to be related to matching the reference mesh.

**Comment by fire** [comment]
Blender has a "align_mesh" tool that can handle rot, loc and scale.

Un-sure about the A pose.

**Comment by PeizhuoLi** [comment]
Hi, our method can only apply to T-pose meshes since  the neural blend shapes is designed to compensate deformation relative to T-pose.

**Comment by fire** [comment]
Thanks.
